In [1]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
import json
from pandas import json_normalize
import numpy as np

In [2]:
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns', None)

In [3]:
cookies = {
    'AWSALBCORS': 'tkz5+9FwjKG66IUKFl+1+74E1+DiKsa+kdwAM5jm6ypn2cV5vaMvRc3filH4XttH24RzbzUe98bpZvbUDAxJowd1zcHeZp3MVpgmmByo3lfa90TB3/xZRtciI+qo',
}

headers = {
    'authority': 'ra.pei.blaize.io',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="99", "Google Chrome";v="99"',
    'x-pei-asset-classes': '1,4,7,8',
    'blaize_session': '7b01eb19-d66a-49ca-86d0-49a5d1c93fbb',
    'sec-ch-ua-mobile': '?0',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36',
    'sec-ch-ua-platform': '"macOS"',
    'accept': '*/*',
    'origin': 'https://www.buyoutsinsider.com',
    'sec-fetch-site': 'cross-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://www.buyoutsinsider.com/',
    'accept-language': 'en-US,en;q=0.9',
    # 'cookie': 'AWSALBCORS=tkz5+9FwjKG66IUKFl+1+74E1+DiKsa+kdwAM5jm6ypn2cV5vaMvRc3filH4XttH24RzbzUe98bpZvbUDAxJowd1zcHeZp3MVpgmmByo3lfa90TB3/xZRtciI+qo',
}

In [4]:
df = pd.read_csv('buyouts_lp_csv/buyouts_lp_orig.csv')
LP_ID = df['ID'].to_list()
print(len(LP_ID))

4146

In [5]:
df1 = pd.DataFrame()

In [6]:
lp_id_list =[]

In [7]:
for i in LP_ID:
    first_part = ('https://ra.pei.blaize.io/api/v2/buyouts/institutions/')
    url = (first_part + str(i) + "/appetite")
    r = requests.get(url, timeout=(10,200), headers=headers, cookies=cookies)
    s = bs(r.content, 'lxml')
    txt = s.get_text()
    if not txt:
        print("no data in " + str(i))
        continue
    lp_id_list.append(i)    
    dict2 = json.loads(txt)
    df1 = df1.append(pd.json_normalize(dict2['data']),ignore_index=True)
    print(str(i) + " done")

3 done
4 done
5 done
8 done
9 done
10 done
14 done
15 done
16 done
18 done
19 done
20 done
23 done
24 done
25 done
26 done
27 done
28 done
30 done
31 done
32 done
33 done
34 done
35 done
37 done
38 done
40 done
41 done
42 done
45 done
48 done
50 done
54 done
55 done
59 done
60 done
62 done
64 done
65 done
66 done
67 done
68 done
71 done
72 done
73 done
74 done
75 done
76 done
78 done
81 done
82 done
83 done
84 done
85 done
86 done
87 done
89 done
90 done
91 done
92 done
93 done
94 done
95 done
96 done
97 done
98 done
99 done
100 done
101 done
107 done
110 done
111 done
112 done
113 done
114 done
115 done
116 done
117 done
118 done
119 done
121 done
122 done
124 done
127 done
128 done
129 done
130 done
131 done
132 done
133 done
135 done
136 done
137 done
139 done
143 done
145 done
146 done
147 done
148 done
150 done
152 done
153 done
154 done
155 done
157 done
158 done
160 done
161 done
162 done
164 done
165 done
166 done
167 done
168 done
170 done
172 done
174 done
175 done
177 done
178 done
179 done
180 done
182 done
184 done
186 done
188 done
189 done
190 done
191 done
193 done
194 done
196 done
198 done
199 done
201 done
202 done
203 done
205 done
206 done
207 done
208 done
209 done
210 done
212 done
213 done
215 done
216 done
217 done
218 done
219 done
220 done
221 done
223 done
224 done
226 done
227 done
229 done
232 done
233 done
234 done
236 done
237 done
238 done
239 done
240 done
241 done
243 done
244 done
245 done
249 done
250 done
251 done
253 done
255 done
257 done
258 done
262 done
263 done
265 done
266 done
267 done
268 done
270 done
271 done
272 done
273 done
274 done
275 done
276 done
282 done
283 done
284 done
285 done
286 done
287 done
288 done
289 done
290 done
291 done
293 done
294 done
295 done
296 done
297 done
300 done
302 done
303 done
304 done
305 done
306 done
307 done
309 done
311 done
314 done
315 done
316 done
318 done
320 done
321 done
322 done
323 done
324 done
325 done
327 done
328 done
329 done
330 done
331 done
336 done
337 done
338 done
340 done
341 done
343 done
344 done
347 done
349 done
350 done
351 done
352 done
354 done
355 done
356 done
357 done
359 done
362 done
364 done
366 done
368 done
369 done
370 done
371 done
372 done
373 done
374 done
375 done
377 done
379 done
381 done
383 done
384 done
386 done
387 done
388 done
389 done
390 done
392 done
394 done
396 done
397 done
399 done
401 done
403 done
404 done
405 done
408 done
409 done
410 done
414 done
415 done
416 done
417 done
418 done
420 done
422 done
423 done
426 done
427 done
428 done
429 done
432 done
433 done
434 done
436 done
437 done
441 done
443 done
445 done
449 done
450 done
451 done
452 done
453 done
454 done
455 done
456 done
457 done
458 done
460 done
461 done
463 done
465 done
466 done
467 done
469 done
470 done
471 done
472 done
474 done
475 done
476 done
477 done
478 done
480 done
481 done
482 done
483 done
484 done
486 done
487 done
489 done
490 done
492 done
495 done
497 done
498 done
499 done
500 done
502 done
504 done
506 done
507 done
508 done
509 done
510 done
511 done
512 done
513 done
514 done
515 done
516 done
517 done
518 done
519 done
520 done
521 done
522 done
523 done
524 done
525 done
526 done
527 done
528 done
530 done
531 done
532 done
533 done
535 done
536 done
537 done
538 done
539 done
540 done
541 done
542 done
543 done
544 done
545 done
546 done
548 done
549 done
550 done
552 done
553 done
554 done
556 done
559 done
560 done
561 done
562 done
563 done
564 done
566 done
567 done
568 done
569 done
572 done
573 done
578 done
581 done
584 done
586 done
587 done
588 done
589 done
591 done
592 done
593 done
594 done
596 done
597 done
598 done
599 done
600 done
603 done
604 done
607 done
609 done
610 done
611 done
612 done
617 done
619 done
620 done
625 done
627 done
630 done
631 done
632 done
633 done
634 done
636 done
639 done
640 done
641 done
644 done
645 done
646 done
647 done
648 done
653 done
654 done
655 done
656 done
657 done
663 done
664 done
667 done
669 done
670 done
671 done
673 done
674 done
675 done
676 done
677 done
681 done
683 done
686 done
687 done
688 done
689 done
691 done
692 done
693 done
694 done
695 done
698 done
700 done
701 done
702 done
706 done
707 done
708 done
709 done
711 done
714 done
715 done
716 done
717 done
719 done
720 done
721 done
722 done
723 done
724 done
725 done
726 done
727 done
728 done
732 done
733 done
734 done
735 done
739 done
740 done
741 done
742 done
745 done
747 done
751 done
752 done
754 done
758 done
761 done
763 done
764 done
766 done
770 done
771 done
772 done
773 done
774 done
775 done
776 done
778 done
779 done
780 done
781 done
782 done
783 done
784 done
785 done
789 done
790 done
791 done
794 done
795 done
796 done
797 done
798 done
799 done
800 done
801 done
802 done
804 done
806 done
808 done
809 done
810 done
813 done
814 done
815 done
817 done
820 done
822 done
823 done
826 done
828 done
829 done
832 done
833 done
839 done
846 done
850 done
851 done
852 done
854 done
861 done
867 done
868 done
876 done
880 done
885 done
886 done
888 done
889 done
892 done
893 done
901 done
902 done
903 done
911 done
914 done
915 done
916 done
921 done
927 done
928 done
929 done
933 done
935 done
939 done
941 done
942 done
944 done
946 done
950 done
954 done
959 done
965 done
975 done
978 done
979 done
987 done
996 done
997 done
1004 done
1005 done
1008 done
1013 done
1015 done
1018 done
1020 done
1022 done
1025 done
1033 done
1034 done
1039 done
1040 done
1041 done
1043 done
1045 done
1046 done
1049 done
1053 done
1056 done
1057 done
1065 done
1067 done
1071 done
1075 done
1079 done
1082 done
1084 done
1086 done
1088 done
1089 done
1097 done
1100 done
1101 done
1102 done
1103 done
1106 done
1107 done
1109 done
1116 done
1117 done
1118 done
1124 done
1128 done
1130 done
1137 done
1139 done
1145 done
1148 done
1150 done
1151 done
1155 done
1160 done
1162 done
1172 done
1173 done
1176 done
1177 done
1181 done
1183 done
1192 done
1194 done
1196 done
1197 done
1198 done
1202 done
1203 done
1211 done
1217 done
1218 done
1220 done
1221 done
1223 done
1228 done
1236 done
1239 done
1241 done
1245 done
1247 done
1248 done
1250 done
1255 done
1260 done
1261 done
1262 done
1264 done
1273 done
1277 done
1284 done
1286 done
1290 done
1292 done
1299 done
1301 done
1307 done
1308 done
1315 done
1317 done
1318 done
1323 done
1324 done
1325 done
1326 done
1327 done
1328 done
1329 done
1330 done
1331 done
1333 done
1335 done
1340 done
1349 done
1355 done
1357 done
1358 done
1359 done
1361 done
1362 done
1366 done
1371 done
1372 done
1375 done
1376 done
1379 done
1382 done
1386 done
1389 done
1392 done
1393 done
1399 done
1402 done
1405 done
1409 done
1410 done
1414 done
1417 done
1422 done
1427 done
1433 done
1435 done
1438 done
1441 done
1447 done
1451 done
1461 done
1462 done
1466 done
1468 done
1470 done
1471 done
1472 done
1473 done
1474 done
1476 done
1478 done
1479 done
1480 done
1481 done
1483 done
1487 done
1488 done
1491 done
1492 done
1493 done
1494 done
1495 done
1497 done
1498 done
1499 done
1500 done
1507 done
1509 done
1510 done
1511 done
1512 done
1513 done
1514 done
1515 done
1516 done
1517 done
1518 done
1519 done
1520 done
1521 done
1522 done
1523 done
1524 done
1525 done
1527 done
1528 done
1529 done
1530 done
1531 done
1533 done
1534 done
1535 done
1538 done
1540 done
1541 done
1542 done
1544 done
1548 done
1549 done
1551 done
1555 done
1556 done
1559 done
1561 done
1562 done
1569 done
1572 done
1573 done
1574 done
1579 done
1582 done
1586 done
1587 done
1588 done
1595 done
1596 done
1597 done
1598 done
1600 done
1603 done
1607 done
1610 done
1615 done
1618 done
1623 done
1625 done
1626 done
1628 done
1633 done
1635 done
1640 done
1649 done
1650 done
1651 done
1655 done
1657 done
1658 done
1663 done
1665 done
1671 done
1672 done
1675 done
1676 done
1678 done
1679 done
1683 done
1687 done
1688 done
1690 done
1695 done
1697 done
1698 done
1699 done
1702 done
1706 done
1708 done
1709 done
1710 done
1713 done
1716 done
1718 done
1721 done
1722 done
1723 done
1724 done
1725 done
1726 done
1727 done
1728 done
1729 done
1732 done
1733 done
1734 done
1735 done
1736 done
1737 done
1738 done
1739 done
1742 done
1745 done
1747 done
1748 done
1751 done
1752 done
1754 done
1757 done

1758 done
1761 done
1762 done
1764 done
1767 done
1768 done
1770 done
1777 done
1779 done
1780 done
1782 done
1784 done
1786 done
1791 done
1796 done
1798 done
1799 done
1800 done
1801 done
1802 done
1806 done
1807 done
1809 done
1811 done
1814 done
1816 done
1818 done
1819 done
1821 done
1822 done
1824 done
1827 done
1830 done
1831 done
1832 done
1837 done
1839 done
1840 done
1841 done
1844 done
1846 done
1847 done
1848 done
1849 done
1851 done
1854 done
1855 done
1857 done
1864 done
1866 done
1867 done
1868 done
1869 done
1870 done
1873 done
1874 done
1875 done
1876 done
1877 done
1878 done
1879 done
1880 done
1881 done
1882 done
1884 done
1885 done
1886 done
1888 done
1889 done
1891 done
1892 done
1894 done
1895 done
1897 done
1899 done
1900 done
1903 done
1905 done
1907 done
1908 done
1911 done
1913 done
1914 done
1915 done
1917 done
1919 done
1920 done
1921 done
1923 done
1924 done
1925 done
1926 done
1929 done
1930 done
1933 done
1934 done
1935 done
1936 done
1939 done
1940 done
1941 done
1943 done
1946 done
1947 done
1952 done
1958 done
1959 done
1961 done
1962 done
1966 done
1968 done
1970 done
1971 done
1972 done
1974 done
1978 done
1985 done
1986 done
1988 done
1992 done
1995 done
2000 done
2002 done
2005 done
2011 done
2015 done
2017 done
2019 done
2020 done
2021 done
2025 done
2026 done
2027 done
2029 done
2030 done
2031 done
2034 done
2037 done
2041 done
2042 done
2043 done
2044 done
2045 done
2046 done
2048 done
2049 done
2050 done
2053 done
2055 done
2056 done
2060 done
2061 done
2062 done
2063 done
2064 done
2065 done
2069 done
2070 done
2071 done
2072 done
2074 done
2076 done
2077 done
2078 done
2079 done
2080 done
2081 done
2082 done
2083 done
2084 done
2087 done
2088 done
2089 done
2093 done
2094 done
2095 done
2097 done
2098 done
2101 done
2103 done
2104 done
2105 done
2106 done
2110 done
2113 done
2118 done
2131 done
2132 done
2135 done
2136 done
2140 done
2145 done
2146 done
2148 done
2149 done
2150 done
2151 done
2152 done
2154 done
2157 done
2161 done
2164 done
2167 done
2170 done
2171 done
2175 done
2176 done
2177 done
2180 done
2187 done
2189 done
2190 done
2192 done
2193 done
2194 done
2200 done
2201 done
2204 done
2206 done
2207 done
2210 done
2211 done
2213 done
2215 done
2220 done
2221 done
2224 done
2228 done
2235 done
2237 done
2238 done
2239 done
2240 done
2242 done
2243 done
2244 done
2245 done
2246 done
2247 done
2248 done
2249 done
2252 done
2253 done
2254 done
2255 done
2259 done
2261 done
2263 done
2264 done
2265 done
2272 done
2274 done
2275 done
2276 done
2279 done
2280 done
2281 done
2282 done
2283 done
2284 done
2287 done
2292 done
2295 done
2296 done
2297 done
2298 done
2299 done
2300 done
2302 done
2308 done
2309 done
2310 done
2311 done
2312 done
2314 done
2316 done
2317 done
2318 done
2319 done
2324 done
2325 done
2326 done
2327 done
2329 done
2331 done
2333 done
2334 done
2338 done
2339 done
2340 done
2342 done
2344 done
2345 done
2346 done
2347 done
2351 done
2352 done
2353 done
2356 done
2358 done
2360 done
2362 done
2364 done
2370 done
2377 done
2394 done
2396 done
2398 done
2399 done
2401 done
2402 done
2403 done
2409 done
2414 done
2416 done
2423 done
2424 done
2430 done
2431 done
2434 done
2439 done
2445 done
2449 done
2453 done
2457 done
2458 done
2464 done
2465 done
2469 done
2472 done
2475 done
2477 done
2479 done
2480 done
2481 done
2485 done
2489 done
2491 done
2495 done
2496 done
2497 done
2498 done
2501 done
2502 done
2503 done
2504 done
2507 done
2510 done
2512 done
2513 done
2515 done
2518 done
2519 done
2522 done
2524 done
2528 done
2532 done
2533 done
2535 done
2536 done
2539 done
2540 done
2544 done
2546 done
2547 done
2548 done
2549 done
2551 done
2552 done
2553 done
2555 done
2558 done
2561 done
2563 done
2568 done
2569 done
2570 done
2571 done
2572 done
2573 done
2574 done
2575 done
2576 done
2577 done
2578 done
2579 done
2582 done
2583 done
2585 done
2586 done
2588 done
2590 done
2596 done
2597 done
2599 done
2600 done
2603 done
2604 done
2607 done
2610 done
2614 done
2615 done
2616 done
2623 done
2625 done
2630 done
2631 done
2632 done
2638 done
2648 done
2651 done
2654 done
2655 done
2656 done
2661 done
2663 done
2668 done
2669 done
2675 done
2676 done
2687 done
2690 done
2691 done
2695 done
2696 done
2704 done
2705 done
2709 done
2712 done
2714 done
2719 done
2735 done
2737 done
2738 done
2750 done
2751 done
2754 done
2755 done
2768 done
2770 done
2778 done
2780 done
2781 done
2786 done
2787 done
2788 done
2790 done
2791 done
2794 done
2796 done
2797 done
2800 done
2801 done
2802 done
2804 done
2806 done
2807 done
2808 done
2809 done
2811 done
2817 done
2818 done
2819 done
2820 done
2823 done
2827 done
2829 done
2831 done
2833 done
2835 done
2838 done
2839 done
2841 done
2842 done
2844 done
2845 done
2847 done
2848 done
2851 done
2852 done
2853 done
2854 done
2855 done
2857 done
2861 done
2862 done
2863 done
2864 done
2865 done
2866 done
2869 done
2870 done
2872 done
2873 done
2874 done
2875 done
2876 done
2877 done
2879 done
2880 done
2884 done
2887 done
2889 done
2890 done
2894 done
2898 done
2901 done
2903 done
2905 done
2906 done
2907 done
2912 done
2915 done
2916 done
2921 done
2925 done
2926 done
2932 done
2934 done
2942 done
2949 done
2951 done
2965 done
2974 done
2977 done
2978 done
2987 done
2994 done
2995 done
3004 done
3005 done
3007 done
3017 done
3018 done
3030 done
3034 done
3038 done
3049 done
3052 done
3065 done
3068 done
3070 done
3073 done
3075 done
3079 done
3083 done
3087 done
3098 done
3102 done
3103 done
3104 done
3105 done
3114 done
3119 done
3121 done
3122 done
3123 done
3124 done
3129 done
3131 done
3142 done
3145 done
3147 done
3155 done
3156 done
3160 done
3163 done
3165 done
3167 done
3169 done
3170 done
3173 done
3176 done
3181 done
3183 done
3188 done
3195 done
3196 done
3197 done
3205 done
3208 done
3211 done
3212 done
3213 done
3215 done
3216 done
3220 done
3221 done
3222 done
3224 done
3231 done
3234 done
3235 done
3238 done
3244 done
3245 done
3246 done
3247 done
3251 done
3254 done
3255 done
3265 done
3273 done
3276 done
3286 done
3290 done
3292 done
3293 done
3294 done
3295 done
3296 done
3297 done
3298 done
3299 done
3300 done
3301 done
3302 done
3305 done
3307 done
3308 done
3311 done
3312 done
3313 done
3316 done
3318 done
3329 done
3335 done
3337 done
3339 done
3344 done
3347 done
3355 done
3357 done
3358 done
3362 done
3365 done
3367 done
3368 done
3371 done
3375 done
3377 done
3378 done
3379 done
3380 done
3381 done
3384 done
3388 done
3390 done
3391 done
3394 done
3395 done
3397 done
3399 done
3400 done
3406 done
3411 done
3412 done
3413 done
3414 done
3416 done
3417 done
3420 done
3422 done
3423 done
3424 done
3428 done
3430 done
3431 done
3433 done
3435 done
3438 done
3439 done
3440 done
3444 done
3445 done
3446 done
3447 done
3451 done
3453 done
3457 done
3458 done
3460 done
3465 done
3468 done
3469 done
3471 done
3475 done
3477 done
3478 done
3479 done
3480 done
3485 done
3486 done
3487 done
3488 done
3490 done
3493 done
3494 done
3497 done
3499 done
3500 done
3501 done
3503 done
3504 done
3505 done
3506 done
3507 done
3508 done
3509 done
3510 done
3513 done
3517 done
3522 done
3525 done
3528 done
3531 done
3533 done
3534 done
3535 done
3537 done
3538 done
3539 done
3541 done
3542 done
3545 done
3559 done
3560 done
3565 done
3568 done
3570 done
3571 done
3576 done
3577 done
3579 done
3584 done
3588 done
3589 done
3590 done
3594 done
3595 done
3600 done
3604 done
3612 done
3613 done
3616 done
3618 done
3619 done
3622 done
3625 done
3628 done
3631 done
3637 done
3638 done
3639 done
3641 done
3647 done
3652 done
3653 done
3654 done
3656 done
3659 done
3662 done
3664 done
3665 done
3667 done
3668 done
3670 done
3671 done
3672 done
3676 done
3677 done
3679 done
3681 done
3682 done
3683 done
3685 done
3687 done
3691 done
3693 done
3701 done
3704 done
3705 done
3709 done
3711 done
3712 done
3714 done
3715 done
3718 done
3719 done
3722 done
3724 done
3727 done
3729 done
3730 done
3733 done
3735 done
3743 done
3745 done
3746 done
3747 done
3748 done
3750 done
3751 done
3754 done
3755 done
3756 done
3759 done
3760 done
3761 done
3762 done
3763 done
3767 done
3775 done
3778 done
3779 done
3780 done
3781 done
3783 done
3786 done
3787 done

3788 done
3789 done
3790 done
3792 done
3793 done
3794 done
3799 done
3801 done
3805 done
3806 done
3808 done
3811 done
3812 done
3814 done
3816 done
3817 done
3818 done
3819 done
3820 done
3822 done
3824 done
3825 done
3826 done
3828 done
3829 done
3831 done
3832 done
3833 done
3837 done
3839 done
3842 done
3843 done
3845 done
3847 done
3851 done
3852 done
3853 done
3854 done
3858 done
3861 done
3863 done
3866 done
3867 done
3868 done
3869 done
3870 done
3871 done
3874 done
3876 done
3877 done
3879 done
3880 done
3881 done
3883 done
3884 done
3885 done
3886 done
3889 done
3890 done
3891 done
3892 done
3893 done
3894 done
3896 done
3897 done
3898 done
3899 done
3900 done
3901 done
3902 done
3904 done
3905 done
3906 done
3907 done
3910 done
3911 done
3912 done
3913 done
3915 done
3916 done
3918 done
3919 done
3923 done
3924 done
3925 done
3929 done
3932 done
3933 done
3934 done
3935 done
3936 done
3937 done
3938 done
3940 done
3944 done
3945 done
3948 done
3949 done
3951 done
3953 done
3954 done
3955 done
3956 done
3958 done
3959 done
3960 done
3961 done
3962 done
3963 done
3965 done
3966 done
3968 done
3969 done
3972 done
3973 done
3974 done
3975 done
3976 done
3977 done
3978 done
3985 done
3988 done
3989 done
3991 done
3992 done
3994 done
3996 done
3998 done
3999 done
4002 done
4005 done
4008 done
4010 done
4011 done
4012 done
4013 done
4018 done
4019 done
4020 done
4024 done
4028 done
4036 done
4037 done
4038 done
4040 done
4042 done
4044 done
4046 done
4048 done
4053 done
4055 done
4056 done
4059 done
4060 done
4061 done
4062 done
4063 done
4064 done
4065 done
4068 done
4072 done
4073 done
4074 done
4075 done
4076 done
4078 done
4082 done
4089 done
4091 done
4095 done
4098 done
4099 done
4101 done
4102 done
4103 done
4106 done
4107 done
4108 done
4112 done
4114 done
4117 done
4121 done
4123 done
4124 done
4126 done
4127 done
4129 done
4130 done
4132 done
4133 done
4136 done
4137 done
4139 done
4140 done
4142 done
4144 done
4146 done
4147 done
4148 done
4150 done
4152 done
4153 done
4156 done
4157 done
4158 done
4161 done
4164 done
4166 done
4167 done
4168 done
4169 done
4170 done
4174 done
4175 done
4177 done
4178 done
4179 done
4180 done
4181 done
4182 done
4183 done
4184 done
4186 done
4192 done
4193 done
4196 done
4197 done
4198 done
4200 done
4202 done
4203 done
4204 done
4205 done
4210 done
4211 done
4213 done
4215 done
4216 done
4217 done
4221 done
4222 done
4226 done
4229 done
4230 done
4231 done
4232 done
4233 done
4234 done
4236 done
4239 done
4240 done
4241 done
4242 done
4243 done
4246 done
4248 done
4253 done
4255 done
4257 done
4259 done
4260 done
4262 done
4266 done
4269 done
4271 done
4272 done
4274 done
4276 done
4278 done
4279 done
4283 done
4284 done
4288 done
4289 done
4290 done
4291 done
4293 done
4294 done
4296 done
4297 done
4300 done
4301 done
4302 done
4304 done
4305 done
4306 done
4309 done
4310 done
4311 done
4313 done
4314 done
4320 done
4321 done
4327 done
4331 done
4333 done
4344 done
4347 done
4350 done
4360 done
4364 done
4366 done
4369 done
4464 done
4506 done
4507 done
4510 done
4513 done
4514 done
4517 done
4518 done
4521 done
4522 done
4523 done
4525 done
4526 done
4527 done
4528 done
4530 done
4536 done
4537 done
4538 done
4540 done
4545 done
4551 done
4555 done
4567 done
4581 done
4586 done
4599 done
4616 done
4622 done
4631 done
4636 done
4638 done
4648 done
4658 done
4665 done
4666 done
4668 done
4678 done
4679 done
4682 done
4692 done
4699 done
4703 done
4709 done
4720 done
4721 done
4733 done
4739 done
4749 done
4750 done
4759 done
4763 done
4769 done
4771 done
4772 done
4773 done
4774 done
4775 done
4790 done
4791 done
4793 done
4799 done
4801 done
4802 done
4808 done
4809 done
4810 done
4812 done
4834 done
4835 done
4836 done
4838 done
4839 done
4840 done
4841 done
4842 done
4843 done
4844 done
4852 done
4854 done
4858 done
4860 done
4861 done
4862 done
4865 done
4867 done
4869 done
4874 done
4879 done
4883 done
4884 done
4887 done
4893 done
4898 done
4899 done
4902 done
4907 done
4922 done
4923 done
4930 done
4933 done
4938 done
4949 done
4950 done
4951 done
4952 done
4953 done
4959 done
4965 done
4966 done
4970 done
4985 done
5012 done
5024 done
5028 done
5035 done
5040 done
5046 done
5055 done
5057 done
5058 done
5065 done
5067 done
5071 done
5078 done
5092 done
5095 done
5096 done
5097 done
5103 done
5105 done
5111 done
5113 done
5118 done
5120 done
5123 done
5124 done
5136 done
5142 done
5147 done
5151 done
5154 done
5158 done
5168 done
5169 done
5178 done
5181 done
5184 done
5187 done
5189 done
5198 done
5209 done
5212 done
5217 done
5218 done
5220 done
5313 done
5322 done
5348 done
5370 done
5401 done
5466 done
5471 done
5528 done
5575 done
5576 done
5578 done
5587 done
5595 done
5598 done
5612 done
5669 done
5671 done
5684 done
5687 done
5692 done
5711 done
5722 done
5760 done
5770 done
5774 done
5794 done
5812 done
5819 done
5860 done
5875 done
5899 done
6159 done
6211 done
6236 done
6311 done
6350 done
6359 done
6361 done
6371 done
6376 done
6389 done
6407 done
6417 done
6440 done
6452 done
6461 done
6467 done
6478 done
6486 done
6487 done
6495 done
6512 done
6515 done
6521 done
6523 done
6536 done
6550 done
6560 done
6562 done
6565 done
6572 done
6573 done
6585 done
6595 done
6600 done
6608 done
6610 done
6635 done
6636 done
6644 done
6668 done
6673 done
6675 done
6680 done
6701 done
6709 done
6744 done
6752 done
6800 done
6804 done
6856 done
6969 done
6972 done
6995 done
7045 done
7085 done
7101 done
7110 done
7229 done
7273 done
7321 done
7364 done
7423 done
7425 done
7454 done
7526 done
7597 done
7604 done
7610 done
7630 done
7634 done
7655 done
7671 done
7699 done
7709 done
7735 done
7753 done
7868 done
7884 done
7918 done
7974 done
7994 done
8004 done
8019 done
8032 done
8051 done
8105 done
8175 done
8180 done
8230 done
8314 done
8322 done
8325 done
8370 done
8378 done
8405 done
8424 done
8429 done
8454 done
8457 done
8620 done
8642 done
8774 done
8793 done
8794 done
8802 done
8804 done
8806 done
8855 done
8862 done
8904 done
8905 done
8915 done
8916 done
8938 done
8940 done
8987 done
9011 done
9025 done
9038 done
9056 done
9058 done
9071 done
9081 done
9086 done
9100 done
9345 done
9647 done
9785 done
10178 done
10257 done
10259 done
10276 done
10281 done
10282 done
10283 done
10284 done
10285 done
10293 done
10296 done
10304 done
10305 done
10308 done
10331 done
10333 done
10340 done
10353 done
10360 done
10361 done
10370 done
10395 done
10396 done
10530 done
10551 done
10598 done
10611 done
10612 done
10617 done
10625 done
10627 done
10628 done
10630 done
10632 done
10635 done
10647 done
10649 done
10653 done
10654 done
10657 done
10660 done
10678 done
10687 done
10694 done
10739 done
10746 done
10749 done
10804 done
10830 done
10836 done
10847 done
10877 done
10915 done
10921 done
10923 done
10925 done
10926 done
10930 done
10938 done
10941 done
10943 done
10956 done
10988 done
10998 done
11004 done
11010 done
11011 done
11060 done
11076 done
11080 done
11087 done
11133 done
11148 done
11149 done
11154 done
11176 done
11249 done
11250 done
11251 done
11252 done
11255 done
11282 done
11287 done
11289 done
11293 done
11331 done
11339 done
11396 done
11408 done
11447 done
11501 done
11518 done
11523 done
11525 done
11532 done
11537 done
11541 done
11542 done
11550 done
11552 done
11568 done
11576 done
11577 done
11585 done
11631 done
11633 done
11666 done
11708 done
11761 done
11767 done
11772 done
11777 done
11783 done
11798 done
11829 done
11858 done
11859 done
11863 done
11888 done
11889 done
11893 done
11902 done
11906 done
11919 done
11925 done
11928 done
11930 done
11931 done
11934 done
11935 done
11936 done
11942 done
11947 done
11948 done
11968 done
11995 done
12004 done
12009 done
12011 done
12014 done
12030 done
12035 done
12037 done
12046 done
12111 done
12240 done
12252 done
12297 done
12338 done
12384 done
12486 done
12493 done
12494 done
12495 done
12497 done
12501 done
12502 done
12524 done
12534 done
12535 done
12550 done
12552 done
12611 done
12629 done
12630 done
12631 done
12640 done
12656 done
12662 done
12664 done
12666 done
12676 done
12716 done
12718 done
12720 done
12722 done
12726 done
12738 done
12739 done
12741 done
12768 done
12779 done
12782 done

12805 done
12822 done
12845 done
12847 done
12856 done
12880 done
12928 done
12936 done
12938 done
12946 done
12948 done
12949 done
12950 done
12956 done
12959 done
12960 done
12967 done
12983 done
12990 done
12992 done
13004 done
13012 done
13014 done
13019 done
13021 done
13065 done
13070 done
13072 done
13075 done
13097 done
13138 done
13145 done
13157 done
13160 done
13163 done
13167 done
13169 done
13177 done
13187 done
13207 done
13223 done
13233 done
13259 done
13292 done
13298 done
13300 done
13309 done
13362 done
13363 done
13369 done
13371 done
13381 done
13406 done
13417 done
13418 done
13429 done
13430 done
13434 done
13451 done
13463 done
13468 done
13496 done
13511 done
13530 done
13536 done
13626 done
13639 done
13647 done
13653 done
13661 done
13666 done
13681 done
13682 done
13685 done
13686 done
13695 done
13699 done
13700 done
13734 done
13735 done
13736 done
13737 done
13739 done
13740 done
13752 done
13761 done
13762 done
13763 done
13767 done
13771 done
13772 done
13773 done
13774 done
13799 done
13804 done
13805 done
13808 done
13826 done
13829 done
13834 done
13835 done
13837 done
13843 done
13847 done
13858 done
13861 done
13862 done
13863 done
13864 done
13867 done
13868 done
13869 done
13870 done
13873 done
13874 done
13880 done
13885 done
13889 done
13890 done
13891 done
13892 done
13893 done
13894 done
13897 done
13899 done
13900 done
13901 done
13904 done
13909 done
13917 done
13920 done
13922 done
13923 done
13925 done
13926 done
13927 done
13928 done
13929 done
13930 done
13931 done
13932 done
13933 done
13935 done
13937 done
13938 done
13939 done
13941 done
13942 done
13945 done
13950 done
13952 done
13954 done
13961 done
13962 done
13964 done
13965 done
13966 done
13967 done
13968 done
13974 done
13982 done
13987 done
13989 done
13990 done
13991 done
13992 done
13995 done
14005 done
14010 done
14015 done
14026 done
14028 done
14029 done
14031 done
14032 done
14033 done
14034 done
14035 done
14038 done
14039 done
14041 done
14042 done
14043 done
14044 done
14046 done
14048 done
14051 done
14052 done
14054 done
14056 done
14059 done
14079 done
14081 done
14082 done
14084 done
14085 done
14086 done
14087 done
14088 done
14089 done
14090 done
14091 done
14094 done
14098 done
14101 done
14112 done
14119 done
14122 done
14123 done
14124 done
14126 done
14128 done
14129 done
14138 done
14155 done
14158 done
14160 done
14162 done
14166 done
14179 done
14180 done
14181 done
14182 done
14183 done
14184 done
14185 done
14186 done
14188 done
14191 done
14199 done
14200 done
14201 done
14202 done
14203 done
14204 done
14206 done
14208 done
14217 done
14219 done
14230 done
14231 done
14232 done
14234 done
14235 done
14236 done
14257 done
14259 done
14260 done
14263 done
14267 done
14268 done
14276 done
14277 done
14282 done
14286 done
14295 done
14296 done
14298 done
14299 done
14300 done
14324 done
14325 done
14326 done
14330 done
14335 done
14339 done
14343 done
14351 done
14361 done
14373 done
14374 done
14388 done
14414 done
14419 done
14421 done
14423 done
14456 done
14460 done
14474 done
14475 done
14476 done
14477 done
14480 done
14493 done
14496 done
14498 done
14499 done
14507 done
14511 done
14517 done
14518 done
14539 done
14543 done
14563 done
14565 done
14567 done
14571 done
14574 done
14598 done
14603 done
14604 done
14620 done
14627 done
14629 done
14633 done
14653 done
14654 done
14660 done
14669 done
14676 done
14677 done
14679 done
14683 done
14684 done
14687 done
14688 done
14721 done
14728 done
14729 done
14730 done
14738 done
14743 done
14755 done
14758 done
14778 done
14786 done
14788 done
14790 done
14793 done
14794 done
14795 done
14796 done
14797 done
14798 done
14800 done
14803 done
14806 done
14807 done
14813 done
14814 done
14816 done
14817 done
14818 done
14819 done
14821 done
14822 done
14830 done
14831 done
14833 done
14835 done
14836 done
14837 done
14838 done
14840 done
14841 done
14842 done
14844 done
14845 done
14846 done
14848 done
14850 done
14851 done
14852 done
14854 done
14856 done
14857 done
14858 done
14860 done
14861 done
14862 done
14864 done
14865 done
14866 done
14869 done
14870 done
14872 done
14873 done
14874 done
14876 done
14878 done
14879 done
14880 done
14883 done
14884 done
14885 done
14889 done
14893 done
14894 done
14895 done
14896 done
14897 done
14900 done
14901 done
14902 done
14904 done
14912 done
14916 done
14920 done
14927 done
14933 done
14937 done
14943 done
14959 done
14960 done
14963 done
14967 done
14968 done
14969 done
14970 done
14971 done
14972 done
14973 done
14978 done
14984 done
14985 done
14986 done
14987 done
14988 done
14989 done
14991 done
15001 done
15004 done
15008 done
15016 done
15029 done
15033 done
15062 done
15075 done
15076 done
15077 done
15078 done
15079 done
15081 done
15088 done
15089 done
15090 done
15091 done
15092 done
15096 done
15111 done
15118 done
15119 done
15125 done
15139 done
15140 done
15141 done
15143 done
15152 done
15155 done
15158 done
15159 done
15161 done
15172 done
15182 done
15189 done
15191 done
15192 done
15197 done
15198 done
15232 done
15249 done
15258 done
15262 done
15263 done
15265 done
15271 done
15272 done
15274 done
15275 done
15276 done
15279 done
15280 done
15283 done
15284 done
15285 done
15286 done
15295 done
15297 done
15298 done
15301 done
15302 done
15306 done
15313 done
15319 done
15320 done
15321 done
15331 done
15332 done
15343 done
15344 done
15345 done
15346 done
15347 done
15349 done
15351 done
15352 done
15353 done
15354 done
15355 done
15365 done
15369 done
15377 done
15382 done
15388 done
15389 done
15391 done
15394 done
15401 done
15425 done
15431 done
15436 done
15442 done
15447 done
15451 done
15459 done
15460 done
15464 done
15466 done
15467 done
15469 done
15470 done
15475 done
15482 done
15494 done
15510 done
15511 done
15513 done
15518 done
15522 done
15530 done
15532 done
15541 done
15542 done
15543 done
15552 done
15554 done
15555 done
15556 done
15557 done
15559 done
15560 done
15561 done
15562 done
15569 done
15570 done
15571 done
15572 done
15573 done
15577 done
15579 done
15585 done
15586 done
15593 done
15595 done
15596 done
15597 done
15598 done
15601 done
15603 done
15605 done
15606 done
15607 done
15618 done
15619 done
15640 done
15645 done
15654 done
15659 done
15663 done
15676 done
15682 done
15691 done
15695 done
15697 done
15698 done
15719 done
15722 done
15725 done
15727 done
15728 done
15730 done
15735 done
15736 done
15745 done
15759 done
15763 done
15769 done
15773 done
15775 done
15781 done
15787 done
15823 done
15848 done
15857 done
15864 done
15865 done
15866 done
15869 done
15871 done
15872 done
15876 done
15880 done
15883 done
15888 done
15890 done
15894 done
15908 done
15914 done
15918 done
15920 done
15941 done
15942 done
15956 done
15973 done
15977 done
16016 done
16019 done
16027 done
16028 done
16030 done
16031 done
16032 done
16033 done
16035 done
16036 done
16038 done
16040 done
16045 done
16046 done
16047 done
16048 done
16049 done
16050 done
16051 done
16053 done
16055 done
16056 done
16057 done
16058 done
16059 done
16063 done
16064 done
16065 done
16076 done
16079 done
16080 done
16082 done
16084 done
16090 done
16093 done
16102 done
16105 done
16110 done
16112 done
16120 done
16121 done
16125 done
16126 done
16127 done
16129 done
16135 done
16137 done
16140 done
16146 done
16148 done
16149 done
16153 done
16154 done
16155 done
16157 done
16159 done
16161 done
16162 done
16168 done
16169 done
16170 done
16172 done
16176 done
16181 done
16186 done
16191 done
16192 done
16193 done
16195 done
16212 done
16214 done
16234 done
16236 done
16238 done
16244 done
16245 done
16246 done
16249 done
16252 done
16263 done
16265 done
16266 done
16267 done
16273 done
16275 done
16276 done
16279 done
16284 done
16285 done
16287 done
16288 done
16289 done
16294 done
16302 done
16305 done
16306 done
16308 done
16309 done
16310 done
16311 done
16312 done
16317 done
16318 done
16319 done
16325 done
16326 done
16327 done
16342 done
16344 done
16345 done
16347 done
16348 done
16349 done
16350 done
16356 done
16357 done
16358 done
16360 done
16361 done
16362 done
16363 done
16369 done
16370 done
16371 done
16375 done
16377 done
16378 done
16379 done
16380 done
16381 done

16382 done
16384 done
16385 done
16390 done
16392 done
16396 done
16398 done
16399 done
16401 done
16411 done
16413 done
16414 done
16417 done
16419 done
16420 done
16421 done
16427 done
16429 done
16432 done
16436 done
16438 done
16439 done
16441 done
16447 done
16450 done
16451 done
16452 done
16460 done
16481 done
16485 done
16487 done
16488 done
16489 done
16491 done
16493 done
16496 done
16499 done
16507 done
16508 done
16513 done
16516 done
16517 done
16518 done
16520 done
16525 done
16535 done
16536 done
16541 done
16545 done
16560 done
16562 done
16568 done
16574 done
16575 done
16576 done
16578 done
16579 done
16586 done
16591 done
16593 done
16594 done
16596 done
16598 done
16599 done
16600 done
16604 done
16606 done
16608 done
16609 done
16610 done
16611 done
16615 done
16621 done
16622 done
16630 done
16638 done
16645 done
16646 done
16647 done
16648 done
16650 done
16660 done
16661 done
16664 done
16666 done
16686 done
16726 done
16733 done
16743 done
16750 done
16757 done
16766 done
16783 done
16790 done
16795 done
16801 done
16807 done
16809 done
16825 done
16831 done
16876 done
16878 done
16879 done
16887 done
16894 done
16895 done
16898 done
16899 done
16907 done
16911 done
16937 done
16954 done
16973 done
16981 done
17012 done
17016 done
17021 done
17028 done
17031 done
17037 done
17043 done
17046 done
17048 done
17049 done
17051 done
17057 done
17075 done
17085 done
17089 done
17091 done
17093 done
17094 done
17095 done
17096 done
17098 done
17103 done
17116 done
17117 done
17118 done
17125 done
17126 done
17128 done
17129 done
17131 done
17133 done
17136 done
17138 done
17143 done
17144 done
17145 done
17146 done
17147 done
17150 done
17154 done
17160 done
17161 done
17162 done
17168 done
17170 done
17176 done
17179 done
17182 done
17187 done
17188 done
17194 done
17196 done
17213 done
17227 done
17229 done
17231 done
17238 done
17239 done
17244 done
17246 done
17249 done
17270 done
17274 done
17277 done
17278 done
17281 done
17285 done
17286 done
17287 done
17288 done
17303 done
17310 done
17320 done
17326 done
17327 done
17333 done
17339 done
17340 done
17342 done
17343 done
17344 done
17345 done
17350 done
17351 done
17353 done
17359 done
17367 done
17368 done
17369 done
17370 done
17371 done
17373 done
17374 done
17375 done
17376 done
17378 done
17379 done
17380 done
17381 done
17383 done
17384 done
17386 done
17388 done
17389 done
17391 done
17393 done
17399 done
17400 done
17402 done
17403 done
17405 done
17406 done
17407 done
17408 done
17409 done
17410 done
17411 done
17413 done
17414 done
17415 done
17416 done
17417 done
17419 done
17420 done
17421 done
17422 done
17423 done
17424 done
17426 done
17427 done
17432 done
17434 done
17436 done
17437 done
17439 done
17440 done
17442 done
17444 done
17445 done
17446 done
17447 done
17448 done
17449 done
17450 done
17451 done
17452 done
17454 done
17456 done
17465 done
17478 done
17480 done
17483 done
17484 done
17486 done
17490 done
17493 done
17495 done
17498 done
17506 done
17507 done
17508 done
17513 done
17516 done
17522 done
17524 done
17525 done
17526 done
17544 done
17545 done
17547 done
17555 done
17556 done
17577 done
17607 done
17628 done
17644 done
17649 done
17655 done
17657 done
17751 done
17752 done
17785 done
17789 done
17797 done
17798 done
17800 done
17815 done
17854 done
17889 done
17891 done
17894 done
17914 done
17915 done
17916 done
17917 done
17918 done
17919 done
17921 done
17923 done
17924 done
17928 done
17929 done
17930 done
17931 done
17932 done
17933 done
17934 done
17936 done
17937 done
17938 done
17939 done
17940 done
17941 done
17942 done
17943 done
17944 done
17945 done
17946 done
17950 done
17951 done
17952 done
17953 done
17958 done
17960 done
17961 done
17962 done
17963 done
17966 done
17968 done
17970 done
17971 done
17973 done
17974 done
17978 done
17979 done
17982 done
17983 done
17989 done
17990 done
17991 done
17992 done
17995 done
17998 done
18006 done
18023 done
18031 done
18034 done
18036 done
18037 done
18040 done
18050 done
18056 done
18057 done
18066 done
18067 done
18068 done
18069 done
18070 done
18071 done
18073 done
18078 done
18084 done
18086 done
18101 done
18102 done
18103 done
18104 done
18105 done
18131 done
18135 done
18158 done
18196 done
18205 done
18214 done
18233 done
18234 done
18238 done
18239 done
18240 done
18248 done
18255 done
18262 done
18292 done
18295 done
18297 done
18307 done
18329 done
18334 done
18335 done
18369 done
18393 done
18410 done
18413 done
18419 done
18432 done
18469 done
18498 done
18504 done
18557 done
18561 done
18565 done
18607 done
18622 done
18670 done
18693 done
18717 done
18735 done
18752 done
18759 done
18775 done
18785 done
18792 done
18805 done
18814 done
18817 done
18892 done
18893 done
18910 done
18929 done
18931 done
18939 done
18942 done
18943 done
18945 done
18948 done
18949 done
18950 done
18951 done
18953 done
18954 done
18955 done
18956 done
18958 done
18959 done
18960 done
18961 done
18962 done
18964 done
18966 done
18967 done
18968 done
18980 done
19031 done
19032 done
19034 done
19035 done
19038 done
19048 done
19059 done
19063 done
19071 done
19086 done
19097 done
19107 done
19108 done
19122 done
19123 done
19127 done
19148 done
19154 done
19157 done
19166 done
19172 done
19200 done
19225 done
19332 done
19345 done
19350 done
19388 done
19419 done
19501 done
19517 done
19544 done
19567 done
19594 done
19619 done
19626 done
19732 done
19739 done
19752 done
19767 done
19800 done
19813 done
19867 done
19874 done
19876 done
19912 done
19968 done
19982 done
19996 done
20018 done
20020 done
20037 done
20043 done
20065 done
20082 done
20099 done
20112 done
20113 done
20116 done
20133 done
20139 done
20141 done
20163 done
20170 done
20187 done
20213 done
20217 done
20229 done
20263 done
20306 done
20320 done
20340 done
20345 done
20375 done
20378 done
20381 done
no data in 20488
20493 done
20519 done
20552 done
20558 done
20580 done
no data in 20592
20594 done
20597 done
20602 done
20603 done
20610 done
20625 done
20626 done
20630 done
20632 done
20633 done
20634 done
20635 done
20636 done
20641 done
20642 done
20643 done
20646 done
20647 done
20648 done
20650 done
20651 done
20652 done
20653 done
20655 done
20656 done
20657 done
20658 done
20662 done
20666 done
20667 done
20675 done
20676 done
20677 done
20678 done
20679 done
20680 done
20682 done
20683 done
20684 done
20685 done
20687 done
20689 done
20690 done
20691 done
20692 done
20693 done
20694 done
20695 done
20696 done
20697 done
20698 done
20699 done
20701 done
20702 done
20703 done
20705 done
20706 done
20710 done
20711 done
20713 done
20715 done
20716 done
20717 done
20719 done
20722 done
20723 done
20724 done
20725 done
20727 done
20728 done
20730 done
20737 done
20738 done
20741 done
20742 done
20744 done
20745 done
20746 done
20747 done
20772 done
20868 done
20887 done
20893 done
20996 done
20997 done
21068 done
21119 done
21120 done
21121 done
21122 done
21124 done
21125 done
21132 done
21136 done
21137 done
21138 done
21139 done
21141 done
21143 done
21144 done
21145 done
21146 done
21150 done
21151 done
21152 done
21154 done
21156 done
21157 done
21158 done
21159 done
21161 done
21162 done
21163 done
21164 done
21165 done
21166 done
21167 done
21168 done
21169 done
21171 done
21173 done
21177 done
21178 done
21179 done
21180 done
21181 done
21182 done
21183 done
21188 done
21189 done
21190 done
21191 done
21192 done
21193 done
21195 done
21196 done
21197 done
21198 done
21199 done
21200 done
21202 done
21203 done
21204 done
21205 done
21206 done
21207 done
21212 done
21214 done
21215 done
21216 done
21217 done
21218 done
21219 done
21220 done
21222 done
21223 done
21224 done
21225 done
21226 done
21227 done
21228 done
21229 done
21230 done
21231 done
21232 done
21237 done
21238 done
21239 done
21240 done
21242 done
21243 done
21246 done
21247 done
21249 done
21250 done
21251 done
21252 done
21257 done
21258 done
21260 done
21261 done
21263 done
21265 done
21266 done
21267 done
21268 done
21269 done
21270 done
21271 done
21273 done
21275 done
21276 done
21278 done
21280 done
21281 done
21285 done
21287 done
21289 done
21294 done
21295 done
21296 done
21297 done
21298 done
21299 done
21300 done
21301 done

21302 done
21303 done
21304 done
21305 done
21307 done
21308 done
21309 done
21310 done
21311 done
21313 done
21314 done
21315 done
21317 done
21319 done
21320 done
21321 done
21322 done
21323 done
21324 done
21325 done
21326 done
21328 done
21329 done
21330 done
21331 done
21332 done
21333 done
21334 done
21335 done
21336 done
21337 done
21338 done
21339 done
21340 done
21345 done
21367 done
21371 done
21372 done
21379 done
21394 done
21397 done
21413 done
21414 done
21435 done
21442 done
21444 done
21456 done
21486 done
21487 done
21488 done
21490 done
21491 done
21493 done
21495 done
21498 done
21504 done
21515 done
21533 done
21534 done
21541 done
21546 done
21547 done
21553 done
21555 done
21572 done
21596 done
21611 done
21645 done
21867 done
21871 done
21877 done
21878 done
21881 done
21882 done
21908 done
21921 done
21925 done
21933 done
21948 done
21949 done
21955 done
no data in 21957
21962 done
21963 done
21964 done
21965 done
21966 done
21968 done
21974 done
21975 done
21980 done
21988 done
21989 done
21990 done
no data in 21992
21994 done
21995 done
no data in 21997
21998 done
22000 done
22001 done
22004 done
no data in 22005
22006 done
22007 done
22008 done
22020 done
22022 done
22037 done
22045 done
22051 done
22052 done
22077 done
22079 done
22081 done
22103 done
22124 done
22125 done
22158 done
22186 done
22188 done
22189 done
22196 done
22203 done
22242 done
22287 done
22291 done
22311 done
22342 done
22404 done
22405 done
22416 done
22421 done
22422 done
22449 done
22568 done
22584 done
22631 done
22723 done
22724 done
22725 done
22750 done
22756 done
22848 done
22849 done
22850 done
22873 done
no data in 22878
22977 done

In [8]:
print(len(lp_id_list))

4139

In [9]:
df1.shape

(4139, 2)

In [10]:
df1.head()

,fundStrategy,sectors
0,"[{'strategy': 'Fund of Funds / Co-Investment', 'regions': ['North America', 'North America', 'Asia-Pacific', 'Asia-Pacific', 'Latin America', 'Latin America', 'Western Europe', 'Western Europe']}]","[{'sector': 'Biotech / Life Science', 'hasAppetite': False}, {'sector': 'Clean Tech / Renewable', 'hasAppetite': False}, {'sector': 'Consumer Goods', 'hasAppetite': False}, {'sector': 'Diversified', 'hasAppetite': True}, {'sector': 'Energy / Oil & Gas', 'hasAppetite': False}, {'sector': 'Financial Services', 'hasAppetite': False}, {'sector': 'Healthcare', 'hasAppetite': True}, {'sector': 'Industrials', 'hasAppetite': False}, {'sector': 'Leisure', 'hasAppetite': False}, {'sector': 'Manufacturing', 'hasAppetite': False}, {'sector': 'Natural Resources', 'hasAppetite': False}, {'sector': 'Other', 'hasAppetite': False}, {'sector': 'Retail', 'hasAppetite': False}, {'sector': 'TMT', 'hasAppetite': True}, {'sector': 'Transport', 'hasAppetite': False}]"
1,"[{'strategy': 'Buyout / Corporate Private Equity', 'regions': ['North America', 'North America', 'Asia-Pacific', 'Asia-Pacific', 'Central/Eastern Europe', 'Central/Eastern Europe', 'Latin America', 'Latin America', 'Middle East/Africa', 'Middle East/Africa', 'Western Europe', 'Western Europe']}, {'strategy': 'Distressed / Turnaround', 'regions': ['North America', 'North America', 'Asia-Pacific', 'Asia-Pacific', 'Central/Eastern Europe', 'Central/Eastern Europe', 'Latin America', 'Latin America', 'Middle East/Africa', 'Middle East/Africa', 'Western Europe', 'Western Europe']}, {'strategy': 'Mezzanine / Debt', 'regions': ['North America', 'North America', 'Asia-Pacific', 'Asia-Pacific', 'Central/Eastern Europe', 'Central/Eastern Europe', 'Latin America', 'Latin America', 'Middle East/Africa', 'Middle East/Africa', 'Western Europe', 'Western Europe']}, {'strategy': 'Venture Capital / Growth Equity', 'regions': ['North America', 'North America', 'Asia-Pacific', 'Asia-Pacific', 'Central/Eastern Europe', 'Central/Eastern Europe', 'Latin America', 'Latin America', 'Middle East/Africa', 'Middle East/Africa', 'Western Europe', 'Western Europe']}]","[{'sector': 'Biotech / Life Science', 'hasAppetite': True}, {'sector': 'Clean Tech / Renewable', 'hasAppetite': True}, {'sector': 'Consumer Goods', 'hasAppetite': True}, {'sector': 'Diversified', 'hasAppetite': True}, {'sector': 'Energy / Oil & Gas', 'hasAppetite': True}, {'sector': 'Financial Services', 'hasAppetite': True}, {'sector': 'Healthcare', 'hasAppetite': True}, {'sector': 'Industrials', 'hasAppetite': True}, {'sector': 'Leisure', 'hasAppetite': False}, {'sector': 'Manufacturing', 'hasAppetite': False}, {'sector': 'Natural Resources', 'hasAppetite': False}, {'sector': 'Other', 'hasAppetite': True}, {'sector': 'Retail', 'hasAppetite': True}, {'sector': 'TMT', 'hasAppetite': True}, {'sector': 'Transport', 'hasAppetite': True}]"
2,"[{'strategy': 'Buyout / Corporate Private Equity', 'regions': ['North America', 'North America', 'Asia-Pacific', 'Asia-Pacific', 'Latin America', 'Latin America', 'Middle East/Africa', 'Middle East/Africa', 'Western Europe', 'Western Europe']}, {'strategy': 'Distressed / Turnaround', 'regions': ['North America', 'North America', 'Asia-Pacific', 'Asia-Pacific', 'Central/Eastern Europe', 'Central/Eastern Europe', 'Latin America', 'Latin America', 'Middle East/Africa', 'Middle East/Africa', 'Western Europe', 'Western Europe']}, {'strategy': 'Mezzanine / Debt', 'regions': ['North America', 'North America', 'Asia-Pacific', 'Asia-Pacific', 'Central/Eastern Europe', 'Central/Eastern Europe', 'Latin America', 'Latin America', 'Middle East/Africa', 'Middle East/Africa', 'Western Europe', 'Western Europe']}, {'strategy': 'Other', 'regions': ['North America', 'North America', 'Asia-Pacific', 'Asia-Pacific', 'Central/Eastern Europe', 'Central/Eastern Europe', 'Latin America', 'Latin America', 'Middle East/Africa', 'Middle East/Africa', 'Western Europe', 'Western Europe']}, {'strategy': 'Venture Capital / Growth Equity', 'regions': ['North America', 'North America', 'Asia-Pacific', 'Asia-Pacific', 'Latin America', 'Latin America', 'Middle East/Africa', 'Middle East/Africa', 'Western Europe', 'Western Europe']}]","[{'sector': 'Biotech / Life Science', 'hasAppetite': False}, {'sector': 'Clean Tech / Renewable', 'hasAppetite': True}, {'sector': 'Consumer Goods', 'hasAppetite': False}, {'sector': 'Diversified', 'hasAppetite': False}, {'sector': 'Energy / Oil & Gas', 'hasAppetite': False}, {'sector': 'Financial Services', 'hasAppetite': True}, {'sector': 'Healthcare', 'hasAppetite': True}, {'sector': 'Industrials', 'hasAppetite': False}, {'sector': 'Leisure', 'hasAppetite': False}, {'sector': 'Manufacturing', 'hasAppetite': True}, {'sector': 'Natural Resources', 'hasAppetite': True}, {'sector': 'Other', 'hasAppetite': True}, {'sector': 'Retail', 'hasAppetite': True}, {'sector': 'TMT', 'hasAppetite': True}, {'sector': 'Transport', 'hasAppetite': True}]"
3,"[{'strategy': 'Buyout / Corporate Private Equity', 'regions': ['North America', 'North America', 'Western Europe', 'Western Europe']}, {'strategy': 'Distressed / Turnaround', 'regions': ['North America', 'North America', 'Western Europe', 'Western Europe']}, {'strategy': 'Mezzanine / Debt', 'regions': ['North America', 'North America', 'Western Europe', 'Western Europe']}, {'strategy': 'Venture Capital / Growth Equity', 'regions': ['North America', 'North America', 'Western Europe', 'Western Europe']}]","[{'sector': 'Biotech / Life Science', 'hasAppetite': False}, {'sector': 'Clean Tech / Renewable', 'hasAppetite': False}, {'sector': 'Consumer Goods', 'hasAppetite': False}, {'sector': 'Diversified', 'hasAppetite': True}, {'sector': 'Energy / Oil & Gas', 'hasAppetite': False}, {'sector': 'Financial Services', 'hasAppetite': True}, {'sector': 'Healthcare', 'hasAppetite': False}, {'sector': 'Industrials', 'hasAppetite': True}, {'sector': 'Leisure', 'hasAppetite': False}, {'sector': 'Manufacturing', 'hasAppetite': False}, {'sector': 'Natural Resources', 'hasAppetite': False}, {'sector': 'Other', 'hasAppetite': False}, {'sector': 'Retail', 'hasAppetite': False}, {'sector': 'TMT', 'hasAppetite': False}, {'sector': 'Transport', 'hasAppetite': False}]"
4,"[{'strategy': 'Buyout / Corporate Private Equity', 'regions': ['North America', 'North America']}, {'strategy': 'Mezzanine / Debt', 'regions': ['North America', 'North America']}]","[{'sector': 'Biotech / Life Science', 'hasAppetite': False}, {'sector': 'Clean Tech / Renewable', 'hasAppetite': False}, {'sector': 'Consumer Goods', 'hasAppetite': True}, {'sector': 'Diversified', 'hasAppetite': True}, {'sector': 'Energy / Oil & Gas', 'hasAppetite': False}, {'sector': 'Financial Services', 'hasAppetite': False}, {'sector': 'Healthcare', 'hasAppetite': False}, {'sector': 'Industrials', 'hasAppetite': False}, {'sector': 'Leisure', 'hasAppetite': False}, {'sector': 'Manufacturing', 'hasAppetite': False}, {'sector': 'Natural Resources', 'hasAppetite': False}, {'sector': 'Other', 'hasAppetite': False}, {'sector': 'Retail', 'hasAppetite': True}, {'sector': 'TMT', 'hasAppetite': False}, {'sector': 'Transport', 'hasAppetite': False}]"

In [11]:
df1['lp_id'] = lp_id_list

In [12]:
df1_strategy= df1.filter(['lp_id','fundStrategy'],axis = 1)

In [17]:
df1_sector = df1.filter(['lp_id','sectors'], axis = 1)

In [18]:
df1_strategy = df1_strategy.explode('fundStrategy')

In [20]:
df1_sector = df1_sector.explode('sectors')

In [21]:
df1_strategy = df1_strategy.join(df1_strategy['fundStrategy'].apply(pd.Series), rsuffix="_l2").explode('regions')

In [22]:
df1_sector = df1_sector.join(df1_sector['sectors'].apply(pd.Series), rsuffix="_l3")

In [31]:
df1_strategy.drop(columns=['fundStrategy',0], axis = 1, inplace = True)

In [34]:
df1_strategy.shape

(428473, 3)

In [32]:
df1_strategy.duplicated().sum()

378728

In [36]:
df1_strategy= df1_strategy.drop_duplicates()

In [55]:
df1_strategy.tail()

      lp_id                 regions                         strategy
4137  22873           North America  Venture Capital / Growth Equity
4137  22873          Western Europe  Venture Capital / Growth Equity
4137  22873  Central/Eastern Europe  Venture Capital / Growth Equity
4137  22873           Latin America  Venture Capital / Growth Equity
4138  22977           North America    Fund of Funds / Co-Investment

In [37]:
df1_sector.head()

,lp_id,sectors,0,hasAppetite,sector
0,3,"{'sector': 'Biotech / Life Science', 'hasAppetite': False}",NaN,False,Biotech / Life Science
0,3,"{'sector': 'Biotech / Life Science', 'hasAppetite': False}",NaN,False,Clean Tech / Renewable
0,3,"{'sector': 'Biotech / Life Science', 'hasAppetite': False}",NaN,False,Consumer Goods
0,3,"{'sector': 'Biotech / Life Science', 'hasAppetite': False}",NaN,True,Diversified
0,3,"{'sector': 'Biotech / Life Science', 'hasAppetite': False}",NaN,False,Energy / Oil & Gas

In [38]:
df1_sector.drop(columns=['sectors',0], axis = 1, inplace = True)

In [39]:
df1_sector.shape

(1003959, 3)

In [40]:
df1_sector.duplicated().sum()

940088

In [42]:
df1_sector =df1_sector.drop_duplicates()

In [48]:
df1_sector.head()

   lp_id hasAppetite                  sector
0      3       False  Biotech / Life Science
0      3       False  Clean Tech / Renewable
0      3       False          Consumer Goods
0      3        True             Diversified
0      3       False      Energy / Oil & Gas

In [47]:
list_col = df1_sector.columns.tolist()

In [50]:
list_col.insert(df1_sector.columns.get_loc('hasAppetite') ,list_col.pop(-1))

In [51]:
df1_sector = df1_sector.reindex(columns= list_col)

In [52]:
df1_sector.head()

   lp_id                  sector hasAppetite
0      3  Biotech / Life Science       False
0      3  Clean Tech / Renewable       False
0      3          Consumer Goods       False
0      3             Diversified        True
0      3      Energy / Oil & Gas       False

In [53]:
df1_sector.to_csv('buyouts_lp_csv/lp_sector.csv', index = False)

In [56]:
df1_strategy.to_csv('buyouts_lp_csv/lp_strategy.csv', index = False)

In [2]:
df2 = pd.read_csv('buyouts_lp_csv/lp_strategy.csv')

In [3]:
df2.head()

   lp_id         regions                           strategy
0      3   North America      Fund of Funds / Co-Investment
1      3    Asia-Pacific      Fund of Funds / Co-Investment
2      3   Latin America      Fund of Funds / Co-Investment
3      3  Western Europe      Fund of Funds / Co-Investment
4      4   North America  Buyout / Corporate Private Equity

In [2]:
df3 = pd.read_csv('buyouts_lp_csv/lp_sector.csv')

In [3]:
df3.head()

   lp_id                  sector hasAppetite
0      3  Biotech / Life Science       False
1      3  Clean Tech / Renewable       False
2      3          Consumer Goods       False
3      3             Diversified        True
4      3      Energy / Oil & Gas       False

In [26]:
dfsector = pd.read_csv('buyouts_lp_csv/lp_sector.csv')

In [31]:
np.random.seed(len(dfsector))
dfsector['sector_id'] = np.random.randint(1, len(dfsector), dfsector.shape[0])

In [32]:
dfsector.head()

   lp_id                  sector hasAppetite  sector_id
0      3  Biotech / Life Science       False      22982
1      3  Clean Tech / Renewable       False      27114
2      3          Consumer Goods       False       2030
3      3             Diversified        True      25874
4      3      Energy / Oil & Gas       False      38533

In [33]:
dfsector.rename(columns={'hasAppetite':'has_appetite'}, inplace=True)

In [34]:
dfsector = dfsector[['sector_id', 'lp_id', 'sector', 'has_appetite']]

In [35]:
dfsector.head()

   sector_id  lp_id                  sector has_appetite
0      22982      3  Biotech / Life Science        False
1      27114      3  Clean Tech / Renewable        False
2       2030      3          Consumer Goods        False
3      25874      3             Diversified         True
4      38533      3      Energy / Oil & Gas        False

In [36]:
dfsector.to_csv('buyouts_lp_csv/lp_sector.csv', index = False)

In [2]:
dfstrategy = pd.read_csv('buyouts_lp_csv/lp_strategy.csv')

In [3]:
np.random.seed(len(dfstrategy))
dfstrategy['strategy_id'] = np.random.randint(1, len(dfstrategy), dfstrategy.shape[0])

In [4]:
dfstrategy.head()

   strategy_id  lp_id         regions                           strategy
0        39405      3   North America      Fund of Funds / Co-Investment
1        40456      3    Asia-Pacific      Fund of Funds / Co-Investment
2        42780      3   Latin America      Fund of Funds / Co-Investment
3        40361      3  Western Europe      Fund of Funds / Co-Investment
4         9061      4   North America  Buyout / Corporate Private Equity

In [5]:
dfstrategy = dfstrategy[['strategy_id', 'lp_id', 'regions', 'strategy']]

In [6]:
dfstrategy.head()

   strategy_id  lp_id         regions                           strategy
0        39405      3   North America      Fund of Funds / Co-Investment
1        40456      3    Asia-Pacific      Fund of Funds / Co-Investment
2        42780      3   Latin America      Fund of Funds / Co-Investment
3        40361      3  Western Europe      Fund of Funds / Co-Investment
4         9061      4   North America  Buyout / Corporate Private Equity

In [7]:
dfstrategy = dfstrategy[['strategy_id', 'lp_id', 'strategy', 'regions']]

In [8]:
dfstrategy.head()

   strategy_id  lp_id                           strategy         regions
0        39405      3      Fund of Funds / Co-Investment   North America
1        40456      3      Fund of Funds / Co-Investment    Asia-Pacific
2        42780      3      Fund of Funds / Co-Investment   Latin America
3        40361      3      Fund of Funds / Co-Investment  Western Europe
4         9061      4  Buyout / Corporate Private Equity   North America

In [9]:
dfstrategy.to_csv('buyouts_lp_csv/lp_strategy.csv', index = False)