In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('buyouts_funds_final.csv')

In [3]:
df.head()

,fund_id,fund_name,fm_id,strategy,sector,region,country,target_fund_size_amt,target_fund_size_currency,fund_size_amt,fund_currency,status,stage,vintage_year,open_date
0,34866,Ascent Venture Partners VII,6381,Venture Capital / Growth Equity,TMT,North America,United States,150000000.0,USD,NaN,NaN,Launched,NaN,2020,2020-0
1,43446,Volunteer Park Capital,19143,Mezzanine / Debt,Diversified,North America,NaN,200000000.0,USD,30000000.0,USD,Currently Investing,1st Close,2019,2019-8
2,44723,Flashstarts Blockchain Fund,14468,Venture Capital / Growth Equity,TMT,North America,United States,6000000.0,USD,NaN,NaN,Launched,NaN,2019,2019-1
3,44727,Harmony Partners IV,10317,Venture Capital / Growth Equity,TMT,North America,United States,125000000.0,USD,NaN,NaN,Launched,NaN,2019,2019-1
4,44738,Light Street Beacon Principals I,19412,Venture Capital / Growth Equity,TMT,North America,United States,20000000.0,USD,NaN,NaN,Launched,NaN,2019,2019-1

In [4]:
df2 = pd.read_csv('/Users/AmeliaMazer/Documents/2022_svb_github/buyouts/buyouts_lp/buyouts_lp_csv/lp_commitments.csv')

In [5]:
df2.head()

,lp_commitment_id,lp_id,fund_id,fund_name,fund_manager_id,fund_manager,sectors,strategies,fund_size_amt,fund_size_currency,commitment_amt,commitment_currency,regions,vintage_year
0,215027,3,60421,Greenspring Global Partners V,7045,StepStone Group,Healthcare,Fund of Funds / Co-Investment,356190000.0,USD,NaN,NaN,Asia-Pacific,2011
1,195565,3,60421,Greenspring Global Partners V,7045,StepStone Group,TMT,Fund of Funds / Co-Investment,356190000.0,USD,NaN,NaN,Asia-Pacific,2011
2,181373,3,60421,Greenspring Global Partners V,7045,StepStone Group,Healthcare,Fund of Funds / Co-Investment,356190000.0,USD,NaN,NaN,Latin America,2011
3,125752,3,60421,Greenspring Global Partners V,7045,StepStone Group,TMT,Fund of Funds / Co-Investment,356190000.0,USD,NaN,NaN,Latin America,2011
4,88550,3,60421,Greenspring Global Partners V,7045,StepStone Group,Healthcare,Fund of Funds / Co-Investment,356190000.0,USD,NaN,NaN,Western Europe,2011

In [6]:
 df_outer = df.merge(df2,how='outer')

In [7]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [8]:
df_outer.head()

,fund_id,fund_name,fm_id,strategy,sector,region,country,target_fund_size_amt,target_fund_size_currency,fund_size_amt,fund_currency,status,stage,vintage_year,open_date,lp_commitment_id,lp_id,fund_manager_id,fund_manager,sectors,strategies,fund_size_currency,commitment_amt,commitment_currency,regions
0,34866,Ascent Venture Partners VII,6381.0,Venture Capital / Growth Equity,TMT,North America,United States,150000000.0,USD,NaN,NaN,Launched,NaN,2020,2020-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,43446,Volunteer Park Capital,19143.0,Mezzanine / Debt,Diversified,North America,NaN,200000000.0,USD,30000000.0,USD,Currently Investing,1st Close,2019,2019-8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,44723,Flashstarts Blockchain Fund,14468.0,Venture Capital / Growth Equity,TMT,North America,United States,6000000.0,USD,NaN,NaN,Launched,NaN,2019,2019-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,44727,Harmony Partners IV,10317.0,Venture Capital / Growth Equity,TMT,North America,United States,125000000.0,USD,NaN,NaN,Launched,NaN,2019,2019-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,44738,Light Street Beacon Principals I,19412.0,Venture Capital / Growth Equity,TMT,North America,United States,20000000.0,USD,NaN,NaN,Launched,NaN,2019,2019-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
from sklearn import cluster

In [ ]:
df_outer.drop(columns =['fund_id','fund_name','status','stage','vintage_year','open_date',\
                              'lp_commitment_id', 'lp_id','fund_manager'], axis = 1)